[package]
edition = "2024"
name = "plugin_http_service"
publish = false
version = "0.1.0"

[[bin]]
name = "plugin_http_service"
path = "src/main.rs"

[dependencies]
axum = { workspace = true }
macro_env_var = { path = "../../crates/macro_env_var" }
macro_entrypoint = { path = "../../crates/macro_entrypoint" }
plugin_platform = { path = "../../crates/plugin_platform" }
rootcause = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["net"] }
tracing = { workspace = true }
workspace-hack = { version = "0.1", path = "../../crates/workspace-hack" }

[dev-dependencies]
async-trait = { workspace = true }
http-body-util = { workspace = true }
tower = { workspace = true }
